--
-- Grants privileges on existing NorthwindStore database objects.
-- Run this after schema.sql, seed.sql, and index.sql so all tables exist.
--

\c northwind
GRANT ALL ON SCHEMA public TO jef;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jef;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jef;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO jef;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO jef;

\c northwind_identity
GRANT ALL ON SCHEMA public TO jef;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jef;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jef;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO jef;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO jef;
